[package]
name = "variables"
version = "2.3.4"
author = ["Vivek Yadav <vivek.yadav472@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
